# -*- coding: utf-8 -*-
"""Remove-duplicate-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nrs_qY7eTsLhujIsKdQ4ul28KSgHblZk
"""

import pandas as pd

# Tải dữ liệu
real1 = pd.read_csv('fake.csv')
real1.shape

# Tìm các dòng dữ liệu bị trùng lặp
duplicates = real1[real1.duplicated('content', keep=False)]
print("Các hàng bị trùng lặp:")
print(duplicates)

# Loại bỏ các hàng bị trùng lặp trong cột 'content', giữ lại bản ghi đầu tiên
real2 = real1.drop_duplicates('content', keep='first')
real2.shape

pip install pandas fuzzywuzzy python-Levenshtein

from fuzzywuzzy import fuzz
from fuzzywuzzy import process

# Thiết lập ngưỡng tương đồng
threshold = 80

# Hàm để tìm các chuỗi gần giống nhau
def find_similar_strings(df, column, threshold):
    similar_pairs = []
    content_list = df[column].tolist()
    for i in range(len(content_list)):
        for j in range(i+1, len(content_list)):
            if fuzz.ratio(content_list[i], content_list[j]) >= threshold:
                similar_pairs.append((content_list[i], content_list[j]))
    return similar_pairs

# Tìm các chuỗi gần giống nhau trong cột 'content'
similar_strings = find_similar_strings(real2, 'content', threshold)

# In ra các cặp chuỗi gần giống nhau
print("Các cặp chuỗi gần giống nhau:")
for pair in similar_strings:
    print(pair)

# Loại bỏ các hàng gần giống nhau, giữ lại bản ghi đầu tiên
unique_content = []
indices_to_keep = []

for i, content in enumerate(real2['content']):
    is_similar = any(fuzz.ratio(content, uc) >= threshold for uc in unique_content)
    if not is_similar:
        unique_content.append(content)
        indices_to_keep.append(i)

real3 = real2.iloc[indices_to_keep]
real3.shape

# Thiết lập ngưỡng tương đồng
threshold2 = 60

# Tìm các chuỗi gần giống nhau trong cột 'content'
similar_strings = find_similar_strings(real3, 'content', threshold2)

# In ra các cặp chuỗi gần giống nhau
print("Các cặp chuỗi gần giống nhau:")
for pair in similar_strings:
    print(pair)

# Loại bỏ các hàng gần giống nhau, giữ lại bản ghi đầu tiên
unique_content2 = []
indices_to_keep2 = []

for i, content in enumerate(real3['content']):
    is_similar = any(fuzz.ratio(content, uc) >= threshold for uc in unique_content2)
    if not is_similar:
        unique_content2.append(content)
        indices_to_keep2.append(i)

real4 = real3.iloc[indices_to_keep2]
real4.shape

from google.colab import files

# Lưu DataFrame real4 vào file CSV
real3.to_csv('new_fake.csv', index=False, encoding='utf-8-sig')

# Tải file CSV về máy
files.download('new_fake.csv')